[package]
name = "luajit-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = { version = "0.71", features = ["runtime"], default-features = false }
cc = { version = "1", default-features = false }
copy_dir = { version = "0.1", default-features = false }
